GemmaConfig:
  vocab_size: <vocab_size_value>  # Replace with actual value
  max_position_embeddings: 8192
  hidden_size: <hidden_size_value>  # Replace with actual value
  intermediate_size: <intermediate_size_value>  # Replace with actual value
  num_hidden_layers: <num_hidden_layers_value>  # Replace with actual value
  num_attention_heads: <num_attention_heads_value>  # Replace with actual value
  head_dim: 256
  num_key_value_heads: <num_key_value_heads_value>  # Replace with actual value
  rms_norm_eps: 1e-6
  rope_theta: 10000.0
  attention_bias: False
  attention_dropout: 0.0
  pad_token_id: null
